language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
sudo: false
install:
  - npm install
script:
  - npm run build

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sed -i '/dist/d' .gitignore; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git remote add origin-dist https://${GH_TOKEN}@github.com/gaspadat/example-babel-node.git; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git add -A .; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git commit -m 'built by travis'; fi
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then git push --force --quiet origin-dist dist; fi
